lens_config:
  start_mode: single
  lock_path: /tmp/JobLens/JobLens.lock
  pid_dir: /tmp/JobLens/node_pids
  max_collector_threads: 4

writers_config:
  buffer_capacity: 4096
  writers:
    - name: es_writer
      type: ESWriter
      config: ES_writer_config

collectors_config:
  job_adder_fifo: /tmp/JobLens/job_adder_fifo
  collectors:
    - name: proc_collector
      type: ProcCollector
      config: proc_collector_config

base_writer_config:
  write_timeout: 5

ES_writer_config:
  host: 192.168.51.85
  port: 9200
  batch_size: 1
  write_timeout: 5
  indexs:
   - collector_name: proc_collector
     index_name: joblens_proc

proc_collector_config:
  freq: 1


file_writer_config:
  path: /tmp/joblens_test
  write_timeout: 5

condor_classads_writer_config:
  write_timeout: 5
  chirp_path: /usr/libexec/condor/condor_chirp
  classads_path: /tmp/classads_test
  chirp_config_dir: /tmp/chirp_configs
  chirp_config_path: /tmp/chirp_configs/used_config

influxdb_writer_config:
  version: 3
  host: 192.168.81.88
  port: 8181
  database: pvm088_test
  token: apiv3_IWvzziQxis-9epEynlSotuaCjhXqUYuc9c7l6vH6qFlAgcwZPHK1rOjXFWW2xadqCPrg8AZm3abi-vDRvQ-91g
  timeout: 5
  mode: async
  batch_size: 1000
  freq: 10
  write_timeout: 5
  influxdb_path: /tmp/influxdb_test

